### ISSUE TITLE
Unable to save state

### ISSUE THREAD

**Issue by nekmao33** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#10]
I've started using your LUA script, which I've slightly modified in terms of commands to adapt it to the French version of the Pokémon Platinum ROM.

I'm using Bizhawk 2.9.1 but I can't get the save states to work via the emulator. I always get the message "Unable to save state" :
<img width="1920" alt="2024-10-29_11h30_38" src="https://github.com/user-attachments/assets/e3b361d3-b744-4392-8e2e-1bb2fd0e7558">

What can I do for this to work ?
I also have another question : If I go back to a previous save state, will the LUA code restart from this save state or from its current progress ?

Thanks !

**Comment by KeeyanGhoreshi** [comment]
Make sure this line in the code is set to a valid path, wherever you want the script to save the states:

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/fd34d955467f06c4528cce95d88561c77c77bf9b/commands/movement.lua#L662

If you want to restart it from a specific state, you will have to comment out all the commands prior to that state in the code.  The states are numbered so they are easy to find in the list of inputs.

**Comment by nekmao33** [comment]
I tried several paths, and even tested the code on another PC. The problem remains the same.
I really don't know what to do...

**Comment by KeeyanGhoreshi** [comment]
try changing the path entirely to something like ` savestate.save('./test.State') , if this works and creates the savestate, then the save functionality is at least working for you.  If not, it might be related to the drive/permissions.  I'd also suggest testing using a simple script devoid of other factors, like so:

```
package.path = "./commands/?.lua;"
console.clear()


movement = loadfile('movement.lua')
m = movement()
scriptName = "Script1"
a = {
    {'save', 'testSave'},

}

m.executeOrders(a)
```

**Comment by nekmao33** [comment]
It works with your 1st method.
Thanks a lot for your help !
