### ISSUE TITLE
Gastly didn't learn Confuse Ray

### ISSUE THREAD

**Issue by nekmao33** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#13]
I'm actually in the Old Château after defeated Fantina.
The training with Gastly went well but, Gastly don't learn Confuse Ray at lvl 19.
Now, Gastly is at lvl 20 with Spite, Mean Look, Curse and Night Shade.
<img width="256" alt="2024-11-01_15h01_33" src="https://github.com/user-attachments/assets/452ccae8-ffe2-4fea-bce5-37b8adfc9d47">

What should I do ?

**Comment by KeeyanGhoreshi** [comment]
Gastly is not meant to learn confuse ray, so this is actually looking correct.  The training in the old chateau should proceed past this point and evolve to haunter, and you should end with a haunter that knows suckerpunch/shadowpunch/curse/nightshade

**Comment by nekmao33** [comment]
Oh... I was confused with that line of code then :
    {'custom10', 16}, -- up to 19 // learn confuse ray

From the comment, I thought he was supposed to learn it, sorry.

**Comment by KeeyanGhoreshi** [comment]
That's very reasonable to think, the comment is ambiguous.
