### ISSUE TITLE
Did something get wrong with Golduck's training at the Old Château ?

### ISSUE THREAD

**Issue by nekmao33** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#16]
Between the 32nd and the 33rd savestate of the 7th part of the game, Smurf the Golduck must train in the Old Château for SPATK EVs.
But, when the 33rd savestate must be done, the game shows this screen (1st frame after the 33rd savestate)
<img width="256" alt="2024-11-06_18h04_08" src="https://github.com/user-attachments/assets/9151899b-2332-4406-8639-8431c6672904">

I suspect the problem to be with either custom6, custom7 and/or custom11 commands since they are repeated multiple times in this section (and probably because I use a French ROM).
I put all the save states of this 7th part in the same Google Drive folder as before : https://drive.google.com/drive/folders/1MXC8x1-0pQKiUjXWmIuoozlPiOCLqiHk?usp=sharing

**Comment by KeeyanGhoreshi** [comment]
oh this is a bug that was supposed to be patched out.  Well not really a bug, just me being lazy :P  

The good news is your training session is likely correctly completed and you can start from savestate 33, so you don't have to redo anything.  I'll add the patch and this should be fixed.

**Comment by nekmao33** [comment]
The patch worked ! Thanks :)
