### ISSUE TITLE
Hearthome Gym desync

### ISSUE THREAD

**Issue by Harpig** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#18]
On script 3, save state 16, the script is supposed to exit the gym to heal and start abusing Eevee to reduce friendship. Instead it starts wandering around the left side of the gym, encountering a trainer, and tries to spin cycle in battle.

Link to Google Drive with all my script 3 save states: https://drive.google.com/drive/folders/1DYQvUx4QRHFlHzjZYMQRexZE1rSC9AbP?usp=sharing

**Comment by KeeyanGhoreshi** [comment]
Yeah, there's not enough buffer time on the b inputs after this battle, so it doesn't settle afterwards before trying to move if there is a long turn prior.  Simple timing issue, fixed with a couple extra b inputs right after the battle.

**Comment by KeeyanGhoreshi** [comment]
should be fixed with #19
