### ISSUE TITLE
Desync at script 7 savestate 5 (bumped into a wandering NPC)

### ISSUE THREAD

**Issue by Harpig** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#21]
At the Galactic Warehouse and after clearing the place out, SOUP uses the Galactic Key to unlock the door and bumps into a wandering scientist, causing him overshoot the stairs, resulting in a desync.

States: https://drive.google.com/drive/folders/1nPSMGf4sikAb78Rjz4UcqbJx363w4f_a?usp=drive_link

**Comment by KeeyanGhoreshi** [comment]
nice catch, this looks like a merge error.  I'll include this fix in my next batch of fixes, just needs to take an extra step up.  Thanks for the help

**Comment by KeeyanGhoreshi** [comment]
addressed in #22
