### ISSUE TITLE
NLua.Exceptions.LuaScriptException: [string "main"]:7: 3.lua:2620: '}' expected (to close '{' at line 246) near '{'

### ISSUE THREAD

**Issue by Pulse-kS** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#23]
Downloaded and ran the new sequence the moment I saw it had been uploaded. Just came back to the emulator & script paused, with this error message in the lua console. SOUP was standing at the southern exit of the bike path, the very first tile after you leave the building.

I presume this is a relatively simple fix? Since my guess is its just a simple syntax error

**Comment by KeeyanGhoreshi** [comment]
oh yah thanks, I'm just stupid.  Syntax error on one of the new lines.
