### ISSUE TITLE
Script 2 cycling road Starly girl

### ISSUE THREAD

**Issue by Harpig** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#26]
Sorry to bother you again Mr. Snack.
I'm not sure what's happening here but SOUP gets stuck trying to shift from Monferno to Monferno, then fumbles around the menus and starts using potions instead of fighting.
[-8__19-HatchedTogepi_607175292.zip](https://github.com/user-attachments/files/17804555/-8__19-HatchedTogepi_607175292.zip)

**Comment by KeeyanGhoreshi** [comment]
looks like there's not enough b inputs after the second starly, monferno's xp is lower than expected.  I'm looking over my notes and I'm starting to realize that I might've been off by 1xp for kricketot... 

Either way, I added some b inputs, which fixes it.

**Comment by Harpig** [comment]
Always those pesky b inputs.

**Comment by KeeyanGhoreshi** [comment]
With how many of these desyncs are caused by lack of sufficient time between button presses I'm half-tempted to just add an 100 frame delay to every single input, balloon the runtime by several hundred hours, and call it a day.
