### ISSUE TITLE
Trapped in contest hall

### ISSUE THREAD

**Issue by Pulse-kS** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#31]
![image](https://github.com/user-attachments/assets/52c06ce7-dd6e-411c-965c-8b76b64d7a08)
Looks like another "didn't buffer enough inputs" desync
Everything looks good up to Script3 21-BeforeRivalBattle, however 22-TogepiEvolves savestate is actually in the rival fight, just as togepi reaches level 19 (unsure if intended or not)
SOUP never leaves Hearthome to train gastly, eventually getting himself stuck in the contest hall for the next 3 scripts
Savestates attached once again:
[Savestates.zip](https://github.com/user-attachments/files/17894683/Savestates.zip)

**Comment by KeeyanGhoreshi** [comment]
this is actually a rare non-buffer related issue lol

Checked my notes, I thought I had checked this one off.

![image](https://github.com/user-attachments/assets/24019735-014f-4098-94eb-df5e0e471833)

Turns out I didn't.  Thanks for the report, will fix this in a moment.
