### ISSUE TITLE
Desync sometime after getting Togepi

### ISSUE THREAD

**Issue by Skroooo** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#34]
It seems like I ran into a desync somewhere during script 3. My current save is "12-BeforeEeveeTraining", while only having two Pokémon and being stuck in a never ending fight, because of empty PP.

![image](https://github.com/user-attachments/assets/7416cbf0-9094-490a-b9fd-dc088c3abe70)
(Screenshot of current state)

I've exited the fight and made some screenshots. Hopefully some of them will help to determine what went wrong.

![image](https://github.com/user-attachments/assets/0d550d8b-70e3-4d0b-870a-2bbca7850896)
![image](https://github.com/user-attachments/assets/4b0329d8-308c-4705-b2dd-38a482d29799)
![image](https://github.com/user-attachments/assets/81f7d645-a1aa-4eb7-8c3e-a40a1e288dd7)
(I don't even know if mail is already important at this point, but better safe than sorry)

Here are also some screenshots of the different savestates prior to my encountering the desync.

![image](https://github.com/user-attachments/assets/7b2f29d6-4e8d-4d91-b9d7-26004806aafd)
![image](https://github.com/user-attachments/assets/43a4429d-da0a-4f2a-acdf-2598af987724)
![image](https://github.com/user-attachments/assets/e26c236e-36e8-46b3-a38f-b440ba7ddde7)
![image](https://github.com/user-attachments/assets/6c717e94-1313-47e9-b99e-3c2ea21a74da)
![image](https://github.com/user-attachments/assets/f417721b-ede6-4d0c-b656-8cf837569aff)
(Savestate 1 through 5 of script 3, in order. After savestate 5 it's only fighting until it has no more PP)

Hope this somehow helps 🦆

**Comment by Skroooo** [comment]
I've tested myself a bit and figured out the exact moment where my game desyncs. It's right before save 01 in script 3, after I exit the cave I'm supposed to press right 21 times (line 453 in 3.lua). During this 21 right presses I run into an NPC blocking my path.
![image](https://github.com/user-attachments/assets/dd16a50c-beb7-47a1-8e25-61dab3dae7e3)
Because of that I don't clear the building to my right, resulting in the desync.

**Comment by KeeyanGhoreshi** [comment]
thanks for finding this and debugging it, you're the best.  I've pushed up a change that fixes this by just pathing along the bottom of oreburgh, which is how it should have been to begin with.
