### ISSUE TITLE
Desync in 4.lua (this may be my own fault, but I would like some reference values so I can check where it broke and if it is indeed my fault or a script error)

### ISSUE THREAD

**Issue by AdmiralCurtiss** [KeeyanGhoreshi/PokemonPlatinumSingleSequence#4]
Now, first I have to say, I admit this is possibly my fault. I futzed around with the initial setup because I was curious how flexible this sequence actually is and whether trainer gender would affect anything, so I picked Dawn with a different trainer name.

I also had an earlier desync in the last gym (the one with the door maze) that I attributed to me accidentally sending some input to Bizhawk, because it ended up encountering trainers in the maze. I manually fixed this and I *think* this shouldn't matter, (I was under the impression that the EXP of those trainer fights went to Eevee who gets some rare candies before the gym leader, fixing the EXP discrepancies), but it is possible this is a byproduct of a much earlier desync that I just didn't notice.

---

I first noticed the desync is right here, where it was trying to cut the tree but no one with Cut was in the party:
https://github.com/user-attachments/assets/a633faed-230c-4da7-98c2-6b4430695d0c

That's shortly after the `26-AfterTrainingGastly` state.

I tried to backtrace it a bit and it looks like Infernape wasn't pulled out of the daycare after `24-AfterInfernapeDaycare`. The script walks up to the daycare, selects to pull out "taxes", and then cancels and walks back out.

I suspect this is an EXP problem with Infernape. It doesn't get a single level during its daycare stay, so the script tries to hit A one too many times to advance the 'your infernape has gained X levels' message. However, I can't find any reference points for what EXP values Infernape *should* be at, so I can't be 100% sure about this.

I checked a few states and Infernape was at 55253 EXP at `10-BeforeMail`, 56385 EXP at `13-InfernapeConsolidated`, and 57724 EXP at `22-OutOfRuins`. I noticed you have a spreadsheet with details in the video but I wasn't able to actually find a link to that spreadsheet, can you maybe tell whether any of those values are correct?

**Comment by KeeyanGhoreshi** [comment]
Very interesting, thank you for the detailed report.  

At `10-BeforeMail` you are at the correct XP value for infernape (around 55250-55280).  

At `13-InfernapeConsolidated` you are also in the correct range, around 56380-56410.

And again at `22-OutOfRuins` you are within the correct range.  So Infernape's XP seems to be tracking correctly.

I'd love to be able to just hand you a list of what XP everyone should be at at each save point, but I don't actually have that information written down anywhere.  

I suspect that the issue is that I made a miscalculation on how many steps are needed to bring all Infernape's up a level, since after the daycare session you will be about 4xp off from level 41.  This daycare session is uncharacteristically precise, I don't know why I didn't just do an extra lap to give myself some buffer.  But it's an easy fix, I will just have that session take a couple more steps.  This hopefully shouldn't affect anything later in the sequence as there is generally more buffer allotted than in this case.

As for your maze problem, the game is supposed to encounter 3 trainers in the maze prior to beginning its loop.  The wandering trainer in the first room, glasses boy in the second room, and the ace trainer also in the second room. This is meant to clear the path for the maze completion later.  If this happened and it still battled a wandering trainer in the maze afterwards, something must've went wrong.

**Comment by AdmiralCurtiss** [comment]
This is the gym trainer that I ended up in that I think was wrong:

![image](https://github.com/user-attachments/assets/7fc4f041-4663-4e11-9ced-22247e2c69eb)

**Comment by KeeyanGhoreshi** [comment]
Yes that is not one of the trainers meant to be battled.  Without further information about what occurred prior to this, whether it was during the loop or before reducing Eevee's friendship, it's difficult to figure out if this is an issue with something in the sequence or if it was just a misinput.

**Comment by AdmiralCurtiss** [comment]
You missed a comma here:

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/commit/c9b9fcca20c475de8245caf75a11abdcb2117af3#diff-c2c0fa71ad3fa4689ec094f3a46a224826f06378591a8f9711e11d3aa3211cacR2061

**Comment by AdmiralCurtiss** [comment]
This did seem to fix the desync at least, it now properly receives Infernape from the daycare with an extra level. I'll monitor this further if it breaks anything later.

**Comment by KeeyanGhoreshi** [comment]
thanks, much appreciated.

**Comment by AdmiralCurtiss** [comment]
Found the next problem... on the state `35-LearningIngrain`, it looks like Togetic reached the level it learns Wish at on the exact same fight Roselia got to Ingrain and the script can't deal with that.

**Comment by AdmiralCurtiss** [comment]
State in case it's helpful: [-1906__35-LearningIngrain_2086953748.zip](https://github.com/user-attachments/files/17536649/-1906__35-LearningIngrain_2086953748.zip)

**Comment by AdmiralCurtiss** [comment]
Hm, maybe I misdiagnosed the cause here, it actually looks okay if I let it run, but the next state at 36 is definitely in the wrong place. I'll check this further later...

**Comment by KeeyanGhoreshi** [comment]
interesting, let me look over that piece of code.  Theoretically, it shouldn't matter that roselia and togetic learn their moves on the same cycle, since right after skipping ingrain, the code is supposed to manage wish.  

Also, unfortunately I can't load your save states, probably a versioning issue.  

I just tested it myself with togetic and roselia leveling up simultaneously, and it works fine as far as I can tell.  Can you describe what is going awry after this?

**Comment by AdmiralCurtiss** [comment]
I'm using BizHawk 2.9.1, in case you want to load the states.

Anyway, forget the thing with the same-fight move, I found the exact problem spot: It's the Jogger on Route 215. He wasn't beaten for me yet, Staravia doesn't get OHKO'd from Infernape's opening move, responds with Whirlwind, and that breaks everything else.

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/88856c53d93c878a658b19a055dbf2a41b2b3e23/commands/4.lua#L4148-L4154

**Comment by AdmiralCurtiss** [comment]
I think it's the `{'press_a', 2},` in line 4150, that causes it to use Cut as the move, but judging by the next two lines you probably wanted to use Close Combat? I'll try changing it to `{'press_a', 1},` and see if that fixes it...

**Comment by KeeyanGhoreshi** [comment]
yes, I'm actually pretty certain why it's written that way lol but it is a bug.  Infernape is meant to use close combat afterwards.

**Comment by KeeyanGhoreshi** [comment]
If you would like to make this change and others yourself and make a PR, I would be happy to approve & merge these changes.  You're doing some invaluable QA right now and deserve some credit :D

**Comment by AdmiralCurtiss** [comment]
Yes, that fixes it, or at least it beats the Jogger correctly now and proceeds to the Black Belt.

Also apologies for jumping to the wrong conclusion and causing unnecessary work, I really should be more patient with these as sometimes the correct sequence looks like nonsense at first glance.

**Comment by KeeyanGhoreshi** [comment]
Also, side note, I was able to load your save state on bizhawk 2.9.1, so if you have further questions/concerns, feel free to comment again here with a savestate if needed.

**Comment by AdmiralCurtiss** [comment]
The next jogger desyncs too lol, seemingly not enough of a wait at the end of the battle so it skips the start of the next walking sequence. I need to stop for today but this should be an easy fix.

**Comment by AdmiralCurtiss** [comment]
Scripts 4 and 5 proceeded without issue now, but 6 desyncs in the Mars fight. It looks like the script is not accounting for Infernape leveling up (and trying to learn Fire Spin) after the Bronzor.

[-1893__07-BeforeMars_1968091678.zip](https://github.com/user-attachments/files/17557732/-1893__07-BeforeMars_1968091678.zip)

**Comment by KeeyanGhoreshi** [comment]
there appears to be some unaccounted for xp in your save state, infernape should not hit fire spin until on or after purugly.  I doubt the sequence could ever acquire xp in a way that doesn't nuke the sequence of inputs, so I'd put it accidentally battling a random trainer or encountering a wild pokemon out of the question.  It's probably some xp from a jogger that is not accounted for in this battle.

Adding the move ignore inputs after bronzor faints should fix this problem

```
{'w', 540}, -- lvlup ignore
{'press_b', 2},
{'w', 1440},
{'press_b', 1}, 
{'w', 540},
{'press_a', 1},
{'w', 600}, -- done
```

There's a chance this occurs again later but infernape never learns another move in the run so it should be an easy fix if it does.  Level up prompts can always be cycled off by either spamming A (move to switch select screen and loop on sending out infernape) or spamming B (keep infernape out and idle on fight menu) depending on whether infernape still needs to be out or not.

**Comment by AdmiralCurtiss** [comment]
This doesn't seem to cause a desync (yet?) but in 7.lua, this block does something weird that I would like a clarification on:

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/fd34d955467f06c4528cce95d88561c77c77bf9b/commands/7.lua#L2021-L2029

This is the next fight after the Cyrus fight. This selects Vaporeon -> Item -> Give -> Sea Incense but then ends up cancelling the whole thing because it's still holding an Iapapa berry from the Cyrus fight that it didn't end up using. I assume this is unintended...?

**Comment by AdmiralCurtiss** [comment]
Something is going wrong here:

https://github.com/KeeyanGhoreshi/PokemonPlatinumSingleSequence/blob/fd34d955467f06c4528cce95d88561c77c77bf9b/commands/7.lua#L2287

It seems like the Sticky Barb isn't where the script expects it in the bag, it scrolls up way too far for it, and also doesn't give it to Togekiss. This is probably gonna be annoying to trace back to the problem source...

[-1718__15-DoneShopping_1204479829.zip](https://github.com/user-attachments/files/17565318/-1718__15-DoneShopping_1204479829.zip)

**Comment by AdmiralCurtiss** [comment]
I'm happy to report that the rest of the scripts ran without issue. Great job!

![image](https://github.com/user-attachments/assets/b2fcbdbd-ea95-4be3-afac-b060b3cf3631)
